name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci-on-linux:
    name: CI on Linux
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            distrod/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.distrod_integration_test/image_cache/**/*.tar.xz
          key: ${{ runner.os }}-test-images

      - name: Run tests
        run: |
          DISTROD_IMAGE_CACHE_DIR="${HOME}/.distrod_integration_test/image_cache" \
          DISTROD_INSTALL_DIR="${HOME}/.distrod_integration_test/install" \
          make test-linux

  ci-on-windows:
    name: CI on Windows
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            distrod/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: |
          touch distrod/distrod_wsl_launcher/resources/distrod_root.tar.gz  # dummy file
          make -f windows.mk test-win
