name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-test-on-linux:
    name: Unit test on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            distrod/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: |
          make unit-test-linux

  integration-test-on-linux:
    name: Integration test on Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro-to-test:
          - ubuntu
          - debian
          - archlinux
          - fedora
          - centos
          - almalinux
          - rockylinux
          - kali
          - mint
          - opensuse
          - amazonlinux
          - oracle
          - gentoo
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            distrod/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.distrod_integration_test/image_cache/**/*.tar.xz
          key: ${{ runner.os }}-test-images-v2

      - name: Install dnsutils
        run: |
          sudo apt-get update
          sudo apt-get install -y dnsutils

      - name: Run tests
        run: |
          export DISTROD_IMAGE_CACHE_DIR="${HOME}/.distrod_integration_test/image_cache" \
          export DISTROD_INSTALL_DIR="${HOME}/.distrod_integration_test/install" \
          export DISTRO_TO_TEST="${{ matrix.distro-to-test }}"
          make integration-test-linux

  test-on-windows:
    name: CI on Windows
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            distrod/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: |
          touch distrod/distrod_wsl_launcher/resources/distrod_root.tar.gz  # dummy file
          make -f windows.mk test-win
